import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'README',
    {
      type: 'category',
      label: 'User Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/README',
        'api-reference/core-api',
        'api-reference/agent-api',
        'api-reference/ui-api',
        'api-reference/utils-api',
        'api-reference/git-api',
        'api-reference/version-api',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/basic-usage',
        'examples/advanced-usage',
        'examples/agent-workflows',
      ],
    },
    'documentation-map',
  ],
};

export default sidebars;
